spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_db?createDatabaseIfNotExist=true
    username: root
    password: dilan
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    open-in-view: false
    show-sql: true
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
event-service:
  url : http://localhost:9798/

service:
  name: event-service
  version: 1.0.0
  url: http://localhost:9798/