server:
  port: 8899
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dilan99x/wednest-config-store
          username: dilan99x
          search-paths:
            - '*service'
          password: dv51102dilan
wednest:
  config:
    store: git repository
